cabal-version: 3.4
name: checked-exceptions
version: 0.3.0.0
synopsis: mtl-style checked exceptions
description: A monad transformer that allows you to throw and catch a restricted set of exceptions, tracked at the type level.
license: MIT
license-file: LICENSE
author: Zachary Churchill
maintainer: zacharyachurchill@gmail.com
homepage: http://github.com/goolord/checked-exceptions
bug-reports: http://github.com/goolord/checked-exceptions/issues
category: Control
build-type: Simple
tested-with:
    GHC == 9.10.1
  , GHC == 9.12.2
  , GHC == 9.14.1
extra-doc-files: CHANGELOG.md, README.md

source-repository head
  type: git
  location: https://github.com/goolord/checked-exceptions.git

common warnings
  ghc-options:
      -Wall
      -Wcompat
      -Widentities
      -Wredundant-constraints

library
  import: warnings
  exposed-modules:
      Control.Monad.CheckedExcept
    , Control.Monad.CheckedExcept.QualifiedDo
  build-depends:
      base >= 4.16 && < 5
    , mtl >= 2.0.0.0 && < 3
    , exceptions >= 0.10 && < 0.11
    , constraints >= 0.13 && < 0.15
  hs-source-dirs: lib
  default-language: GHC2021

library plugin
  import: warnings
  visibility: public
  exposed-modules:
      Control.Monad.CheckedExcept.Plugin
  other-modules:
      Control.Monad.CheckedExcept.Plugin.Defaulting
  build-depends:
      checked-exceptions
    , base >= 4.16 && < 5
  if impl(ghc >= 9.14)
    build-depends: ghc >= 9.14 && < 9.15
  elif impl(ghc >= 9.12)
    build-depends: ghc >= 9.12 && < 9.13
  elif impl(ghc >= 9.10)
    build-depends: ghc >= 9.10 && < 9.11
  else
    buildable: False
  hs-source-dirs: lib
  default-language: GHC2021

test-suite test
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  other-modules:
      CompTest
    , NegTest
    , RuntimeTest
  build-depends:
      HUnit
    , tasty
    , base
    , tasty-hunit
    , checked-exceptions
    , checked-exceptions:plugin
    , mtl
    , transformers
    , exceptions
  ghc-options:
      -Wall
      -dcore-lint
      -fplugin Control.Monad.CheckedExcept.Plugin
  default-language: GHC2021
